language: java

branches:
  only:
    - master

# https://travis-ci.community/t/error-installing-oraclejdk8-expected-feature-release-number-in-range-of-9-to-14-but-got-8/3766/5
dist: trusty

jdk:
  - oraclejdk8

after_success:
  - mvn clean test jacoco:report coveralls:report